<?php

return array (
  'SUPPORT_EMAIL' => 'support@clovereader.com',
  'SUPPORT_PHONE' => '+44 808 502 0267',
  'SUPPORT_HOURS' => 'Monday - Friday 08:00-24:00 (CET), Weekends 10:00 - 18:00 (CET)',
  'SUPPORT_LANGUAGES' => 'French, Italian, English',
  'CONCEPT_NAME' => 'CloveReader',
  'COMPANY_NAME' => 'MELEMELE LTD',
  'COMPANY_BUSINESS_NUMBER' => 'ΗΕ 436100',
  'COMPANY_VAT_NUMBER_AREA' => 'EU',
  'COMPANY_VAT_NUMBER' => 'CY10436100D',
  'COMPANY_ADDRESS' => 'Stylianou Lena 3, Flat/Office 5',
  'COMPANY_POSTCODE' => '2236',
  'COMPANY_CITY' => 'Nicosia',
  'COMPANY_COUNTRY' => 'Cyprus',
  'COMPANY_COUNTRY_CODE' => 'CY',
  'COMPANY_REGISTRATION_DATE' => '2022-07-04',
  'CONCEPT_WEBSITE_NAME' => 'clovereader.com',
  'CAMPAIGN_DOMAIN' => 'https://checkout.clovereader.com/en/c/clovereader-signup',
  'CAMPAIGN_DOMAIN_URL' => 'https://checkout.clovereader.com',
  'SERVICE_UNIQUE_ID_TOKEN' => '4a644f12b48c',
  'COMPANY_VAT_NUMBER_AREA_1' => 'EU',
  'COMPANY_VAT_NUMBER_EU' => 'CY10436100D',
  'COMPANY_VAT_NUMBER_AREA_2' => 'GB',
  'COMPANY_VAT_NUMBER_GB' => 'GB 447 8408 62',
  'COMPANY_VAT_NUMBER_AREA_3' => 'AU',
  'COMPANY_VAT_NUMBER_AU' => '300031123540',
  'COMPANY_VAT_NUMBER_AREA_4' => 'CA',
  'COMPANY_VAT_NUMBER_CA' => '775776156RT9999',
  'COMPANY_VAT_NUMBER_AREA_5' => 'NO',
  'COMPANY_VAT_NUMBER_NO' => '2083574',
);